- name: Install rustup
  ansible.builtin.package:
    name: rustup
    state: present
  become: "{{ ansible_facts['os_family'] == 'Debian' }}"

- name: Set default Rust toolchain (Debian/Ubuntu)
  ansible.builtin.command:
    cmd: rustup default stable
  register: rustup_default
  changed_when: "'installing' in rustup_default.stdout"
  when: ansible_facts['os_family'] == "Debian"

- name: Install Rust language server
  ansible.builtin.command:
    cmd: rustup component add rust-analyzer
  register: rust_analyzer_install
  changed_when: "'installing' in rust_analyzer_install.stdout"

- name: Install RustRover
  ansible.builtin.package:
    name: rustrover
    state: present
  when: ansible_facts['os_family'] == "Darwin"
