- name: Android
  hosts: localhost
  tasks:
    - name: Install Android Studio
      ansible.builtin.package:
        name: android-studio
        state: present

- name: Web
  hosts: localhost
  tasks:
    - name: Install Node 20
      ansible.builtin.package:
        name: node@20
        state: present
    - name: Install google-cloud-sdk
      ansible.builtin.package:
        name: google-cloud-sdk
        state: present
    - name: Install gke-gcloud-auth-plugin
      ansible.builtin.command:
        cmd: "gcloud components install gke-gcloud-auth-plugin"
    - name: Install IntelliJ IDEA
      ansible.builtin.package:
        name: intellij-idea
        state: present
