---
- hosts: localhost
  roles:
    - android
    - languages/cpp
    - desktop
    - languages/rust
    - languages/javascript
    - languages/typescript
    - cloud
    - containerization
    - network
    - ai
    - terminal
