---
- hosts: localhost
  roles:
    - android
    - languages/cpp
    - desktop
    - languages/rust
    - languages/javascript
    - languages/typescript
    - languages/python
    - cloud
    - containerization
    - k8s
    - network
    - role: ai
      tasks_from: node.yaml
    - role: ai
      tasks_from: claude-code.yaml
    - role: ai
      tasks_from: codex.yaml
    - terminal
