- name: Install cat replacement
  ansible.builtin.package:
    name: bat
    state: present
- name: Install bandwhich
  ansible.builtin.package:
    name: bandwhich
    state: present
- name: Install top replacement
  ansible.builtin.package:
    name: bottom
    state: present
- name: Install du replacement
  ansible.builtin.package:
    name: dust
    state: present
- name: Install ping replacement
  ansible.builtin.package:
    name: gping
    state: present
- name: Install time replacement
  ansible.builtin.package:
    name: hyperfine
    state: present
- name: Install find replacement
  ansible.builtin.package:
    name: fd
    state: present
- name: Install ps replacement
  ansible.builtin.package:
    name: procs
    state: present
- name: Install grep replacement
  ansible.builtin.package:
    name: ripgrep
    state: present
- name: Install rm replacement
  ansible.builtin.package:
    name: rm-improved
    state: present
- name: Install traceroute replacement
  ansible.builtin.package:
    name: trippy
    state: present
- name: Install cloc replacement
  ansible.builtin.package:
    name: tokei
    state: present
- name: Install terminal replacement
  ansible.builtin.package:
    name: Warp
    state: present
- name: Install cd replacement
  ansible.builtin.package:
    name: zoxide
    state: present
